/** Prefer for rendering spirit glyphs (avoids blank boxes in some Electron/Linux setups). */
export const SPIRIT_EMOJI_FONT_STACK =
  '"Apple Color Emoji","Segoe UI Emoji","Noto Color Emoji","Twemoji Mozilla","EmojiOne Color",sans-serif';

/** Slugs stored in `reps.spirit_animal` and sent on `CelebrationEvent.repHero`. */
export const SPIRIT_ANIMALS = [
  { id: "", label: "None", emoji: "" },
  { id: "wolf", label: "Wolf", emoji: "🐺" },
  { id: "eagle", label: "Eagle", emoji: "🦅" },
  { id: "falcon", label: "Falcon", emoji: "🦅" },
  { id: "hawk", label: "Hawk", emoji: "🦅" },
  { id: "owl", label: "Owl", emoji: "🦉" },
  { id: "crow", label: "Crow", emoji: "🐦" },
  { id: "parrot", label: "Parrot", emoji: "🦜" },
  { id: "peacock", label: "Peacock", emoji: "🦚" },
  { id: "flamingo", label: "Flamingo", emoji: "🦩" },
  { id: "duck", label: "Duck", emoji: "🦆" },
  { id: "swan", label: "Swan", emoji: "🦢" },
  { id: "turkey", label: "Turkey", emoji: "🦃" },
  { id: "chicken", label: "Chicken", emoji: "🐔" },
  { id: "rooster", label: "Rooster", emoji: "🐓" },
  { id: "tiger", label: "Tiger", emoji: "🐯" },
  { id: "lion", label: "Lion", emoji: "🦁" },
  { id: "leopard", label: "Leopard", emoji: "🐆" },
  { id: "cat", label: "Cat", emoji: "🐱" },
  { id: "black_cat", label: "Black cat", emoji: "🐈" },
  { id: "fox", label: "Fox", emoji: "🦊" },
  { id: "dog", label: "Dog", emoji: "🐕" },
  { id: "poodle", label: "Poodle", emoji: "🐩" },
  { id: "bear", label: "Bear", emoji: "🐻" },
  { id: "panda", label: "Panda", emoji: "🐼" },
  { id: "koala", label: "Koala", emoji: "🐨" },
  { id: "rabbit", label: "Rabbit", emoji: "🐰" },
  { id: "mouse", label: "Mouse", emoji: "🐭" },
  { id: "rat", label: "Rat", emoji: "🐀" },
  { id: "hamster", label: "Hamster", emoji: "🐹" },
  { id: "hedgehog", label: "Hedgehog", emoji: "🦔" },
  { id: "raccoon", label: "Raccoon", emoji: "🦝" },
  { id: "badger", label: "Badger", emoji: "🦡" },
  { id: "otter", label: "Otter", emoji: "🦦" },
  { id: "skunk", label: "Skunk", emoji: "🦨" },
  { id: "monkey", label: "Monkey", emoji: "🐵" },
  { id: "gorilla", label: "Gorilla", emoji: "🦍" },
  { id: "orangutan", label: "Orangutan", emoji: "🦧" },
  { id: "horse", label: "Horse", emoji: "🐴" },
  { id: "unicorn", label: "Unicorn", emoji: "🦄" },
  { id: "zebra", label: "Zebra", emoji: "🦓" },
  { id: "deer", label: "Deer", emoji: "🦌" },
  { id: "bison", label: "Bison", emoji: "🦬" },
  { id: "cow", label: "Cow", emoji: "🐮" },
  { id: "pig", label: "Pig", emoji: "🐷" },
  { id: "boar", label: "Boar", emoji: "🐗" },
  { id: "ram", label: "Ram", emoji: "🐏" },
  { id: "goat", label: "Goat", emoji: "🐐" },
  { id: "camel", label: "Camel", emoji: "🐪" },
  { id: "llama", label: "Llama", emoji: "🦙" },
  { id: "giraffe", label: "Giraffe", emoji: "🦒" },
  { id: "elephant", label: "Elephant", emoji: "🐘" },
  { id: "rhino", label: "Rhino", emoji: "🦏" },
  { id: "hippo", label: "Hippo", emoji: "🦛" },
  { id: "dolphin", label: "Dolphin", emoji: "🐬" },
  { id: "whale", label: "Whale", emoji: "🐋" },
  { id: "shark", label: "Shark", emoji: "🦈" },
  { id: "fish", label: "Fish", emoji: "🐟" },
  { id: "tropical_fish", label: "Tropical fish", emoji: "🐠" },
  { id: "blowfish", label: "Blowfish", emoji: "🐡" },
  { id: "octopus", label: "Octopus", emoji: "🐙" },
  { id: "squid", label: "Squid", emoji: "🦑" },
  { id: "lobster", label: "Lobster", emoji: "🦞" },
  { id: "crab", label: "Crab", emoji: "🦀" },
  { id: "shrimp", label: "Shrimp", emoji: "🦐" },
  { id: "snail", label: "Snail", emoji: "🐌" },
  { id: "butterfly", label: "Butterfly", emoji: "🦋" },
  { id: "bee", label: "Bee", emoji: "🐝" },
  { id: "ladybug", label: "Ladybug", emoji: "🐞" },
  { id: "ant", label: "Ant", emoji: "🐜" },
  { id: "spider", label: "Spider", emoji: "🕷" },
  { id: "scorpion", label: "Scorpion", emoji: "🦂" },
  { id: "snake", label: "Snake", emoji: "🐍" },
  { id: "lizard", label: "Lizard", emoji: "🦎" },
  { id: "turtle", label: "Turtle", emoji: "🐢" },
  { id: "crocodile", label: "Crocodile", emoji: "🐊" },
  { id: "frog", label: "Frog", emoji: "🐸" },
  { id: "penguin", label: "Penguin", emoji: "🐧" },
  { id: "bird", label: "Bird", emoji: "🐦" },
  { id: "bat", label: "Bat", emoji: "🦇" },
  { id: "dragon", label: "Dragon", emoji: "🐉" },
  { id: "t_rex", label: "T-Rex", emoji: "🦖" },
  { id: "sauropod", label: "Sauropod", emoji: "🦕" },
  { id: "phoenix", label: "Phoenix", emoji: "✨" },
  { id: "seal", label: "Seal", emoji: "🦭" },
] as const;

export type SpiritAnimalId = (typeof SPIRIT_ANIMALS)[number]["id"];

export function spiritAnimalEmoji(id: string): string {
  const row = SPIRIT_ANIMALS.find((a) => a.id === id);
  return row?.emoji ?? "";
}

export function spiritAnimalLabel(id: string): string {
  const row = SPIRIT_ANIMALS.find((a) => a.id === id);
  return row?.label ?? "";
}
